name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ipfs-uploader/yarn.lock

      - name: Install yarn
        run: npm install -g yarn

      - name: Install and Build
        run: |
          cd ipfs-uploader
          yarn install
          yarn build
      
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ipfs-uploader/dist/
          server-dir: ${{ secrets.FTP_DIRECTORY }}
          dangerous-clean-slate: true
